# Generated by Django 3.2 on 2025-02-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_vehicleproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleproject',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
