# Generated by Django 3.2 on 2025-02-14 03:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_vehicleproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleproject',
            name='vehicle_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/da2p6g2oi/image/upload/v1735245606/fqtofhhdsgammwjmtywe.jpg', max_length=255, verbose_name='image'),
        ),
    ]
