# Generated by Django 3.2 on 2025-02-14 03:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_vehicleproject_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleproject',
            name='vehicle_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/da2p6g2oi/image/upload/v1739504591/pexels-bjbaba-20534679_rajv0w.jpg', max_length=255, verbose_name='image'),
        ),
    ]
