# Generated by Django 3.2 on 2025-02-14 03:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_vehicleproject_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleproject',
            name='vehicle_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/da2p6g2oi/image/upload/v1739504776/depositphotos_247872612-stock-illustration-no-image-available-icon-vector_fzapaw.webp', max_length=255, verbose_name='image'),
        ),
    ]
