# Generated by Django 4.2.16 on 2024-10-13 17:34

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        # No operations needed if "challenge" field already exists.
    ]
