# Generated by Django 4.2.16 on 2024-10-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_about_comment_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
