# Generated by Django 3.2 on 2025-02-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_projectlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
